import { type IMetaLayout } from './MetaLayout.types'

export const metaLayoutMock: IMetaLayout = {
    title: 'Haneul Choi | Software Developer & Mathematics Tutor',
    description:
        'Hi, my name is Haneul Choi. I am a software developer & mathematics tutor based in California. Visit my portfolio page to learn about how you can work with me on your next software project.',
    keywords: [
        'Haneul Choi',
        'haneulchoi',
        'Haneulab',
        'HaneuLab',
        'haneulab',
        'software developer',
        'frontend developer',
        'backend developer',
        'web application',
        'websites',
        'business websites',
        'ecommerce websites',
        'portfolio websites',
        'software programs',
        'Mathematics',
        'mathematics',
        'Computer Science',
        'computer science',
        'Math Tutor',
        'math tutor',
        'Computer Science Tutor',
        'computer science tutor',
        'SAT Math',
        'sat math',
        'SAT Tutor',
        'sat tutor',
        'software programs',
        'university of california, davis',
        'University of California, Davis',
        'uc davis',
        'UC Davis',
        'mathematics',
        'Mathematics',
        'probability',
        'Probability',
        'combinatorics',
        'Combinatorics',
    ],
    image: 'public/logo.png',
}
